# Generated by Django 4.2.5 on 2023-09-23 16:23

from django.db import migrations, models
import django.db.models.deletion
import history.entity.country
import history.entity.inventory_status


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DonorOrganization",
            fields=[
                (
                    "street",
                    models.CharField(help_text="street address", max_length=128),
                ),
                ("city", models.CharField(max_length=64)),
                (
                    "province_state",
                    models.CharField(help_text="province/state/region", max_length=64),
                ),
                (
                    "country",
                    models.CharField(
                        default=history.entity.country.Country.default_number, max_length=32
                    ),
                ),
                ("phone_area_code", models.CharField(max_length=3)),
                ("phone_number", models.CharField(max_length=7)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "user_key_create",
                    models.CharField(
                        default="Y8o7VtuzeetNO24ji2Iit0zR4fQexsG9nLAZwqBFiDGvopEGddBvCZNSEmHTTT7zwblVonVis5S2BzFVELi8aNsXp1YjaJcFND8U5S3Pc0S0hwIC7gdmwQqqc9Wr3b",
                        max_length=128,
                    ),
                ),
                (
                    "donor_organization_id",
                    models.CharField(
                        default="n5eG0LsD9WtlSp9gCoyWwFEOv32ofORAnFiaxOb632T2PytQS3rPkWYExSZP228ClVJGLtulm2A1KzsRnRArt14gBCIUgqbltnaW6ZtMDt8BCDTWJNQjC4QhlbqfbM",
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("url", models.URLField(default="")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DonorPerson",
            fields=[
                (
                    "street",
                    models.CharField(help_text="street address", max_length=128),
                ),
                ("city", models.CharField(max_length=64)),
                (
                    "province_state",
                    models.CharField(help_text="province/state/region", max_length=64),
                ),
                (
                    "country",
                    models.CharField(
                        default=history.entity.country.Country.default_number, max_length=32
                    ),
                ),
                ("phone_area_code", models.CharField(max_length=3)),
                ("phone_number", models.CharField(max_length=7)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "user_key_create",
                    models.CharField(
                        default="Y8o7VtuzeetNO24ji2Iit0zR4fQexsG9nLAZwqBFiDGvopEGddBvCZNSEmHTTT7zwblVonVis5S2BzFVELi8aNsXp1YjaJcFND8U5S3Pc0S0hwIC7gdmwQqqc9Wr3b",
                        max_length=128,
                    ),
                ),
                (
                    "donor_person_id",
                    models.CharField(
                        default="ShLjjnZeY4RkwAy7eKRzE6XW1PnQHUaW7KY0O6fJ4GJPsNVICtg1ucA98cmVXxNFFfzMYGF8JJ0FYE8Zvwl8texcrs1XSLXfpaqTI5KEv0HRuKaxeuHdZBarkVWeUm",
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("last_name", models.CharField(max_length=32)),
                ("first_name", models.CharField(max_length=64)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                ("name", models.CharField(max_length=128)),
                (
                    "inventory_item_id",
                    models.CharField(
                        default="idtDKGXLiwQSWTyE9OFJeFQejbwgJccl1HOEcrLY3tRGELT5WjllZxq2FVyTtWTlYsAEsCPK5wL78YL3Qkf2KiqkaSVpG8CAbBHPaCa4fgAJgi4UQEGnh7JHXAsN6C",
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("user_key_create", models.CharField(default="", max_length=128)),
                ("date_received", models.DateTimeField(null=True)),
                ("date_registered", models.DateTimeField(null=True)),
                ("date_entered", models.DateTimeField(null=True)),
                ("disposal_terms", models.TextField(default="")),
                ("address_community", models.TextField(default="")),
                ("donated_at", models.DateTimeField(null=True)),
                (
                    "title",
                    models.CharField(
                        default="",
                        help_text="unique name, for conversational reference",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="",
                        help_text="a paragraph, eg. that would tell someone something interesting about the item",
                    ),
                ),
                ("part_of", models.TextField(default="")),
                ("description_level", models.TextField(default="")),
                ("biography", models.TextField(default="")),
                (
                    "url",
                    models.URLField(
                        default="",
                        help_text="if such exists, a url that we link to that provides more detail about the item",
                        null=True,
                    ),
                ),
                (
                    "accession_id",
                    models.CharField(
                        default="",
                        help_text="unique identifier, eg. ISBN",
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(default="")),
                ("scope_and_content", models.TextField(default="")),
                ("related_material", models.TextField(default="")),
                ("name_access", models.TextField(default="")),
                ("subject_access", models.TextField(default="")),
                ("gmd", models.TextField(default="")),
                ("gmd_start", models.DateTimeField(null=True)),
                ("gmd_end", models.DateTimeField(null=True)),
                ("date_range_start", models.DateTimeField(null=True)),
                ("date_range_end", models.DateTimeField(null=True)),
                ("registered_at", models.DateTimeField(null=True)),
                ("manufacturer", models.TextField(default="unknown")),
                ("manufactured_from", models.DateTimeField(null=True)),
                ("manufactured_through", models.DateTimeField(null=True)),
                ("manufactured_in", models.CharField(default="", max_length=128)),
                ("manufacture_technique", models.CharField(default="", max_length=128)),
                ("physical_description", models.TextField(default="")),
                ("physical_condition", models.TextField(default="")),
                ("inscription", models.CharField(default="", max_length=128)),
                ("length", models.IntegerField(default=0)),
                ("width", models.IntegerField(default=0)),
                ("height", models.IntegerField(default=0)),
                ("title_page_title", models.TextField(default="")),
                ("spine_title", models.TextField(default="")),
                ("edition", models.TextField(default="")),
                ("numbered_pages", models.IntegerField(default=0)),
                ("is_hardcover", models.BooleanField(default=True)),
                ("cover_color", models.TextField(default="")),
                ("record_type", models.TextField(default="")),
                ("subject_names", models.TextField(default="")),
                ("summary", models.TextField(default="")),
                (
                    "donor_organization_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="history.donororganization",
                    ),
                ),
                (
                    "donor_person_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="history.donorperson",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryLocation",
            fields=[
                (
                    "inventory_location_id",
                    models.CharField(
                        default="VqiScfxyJjYPnIop7hxRbCRED94sO0CHDgj0sx3egh9gKApnQgefeqyhuPCldhaWWbhzeqx0bTnHHDIkw41gJnCXSlRXleBwATJ46psLylJf7yYNGIT9Pj0jcPF8ty",
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(default=None)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("user_key_create", models.CharField(default=None, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="InventoryStatus",
            fields=[
                (
                    "inventory_status_id",
                    models.CharField(
                        default="xby3BLnNE2OEXTR9qSjbRKt9TTzOr2zgTLTEeI71T2T9G5HY3idtQlYGMca28JIeQFCTyhGa65iig4R05ymManOkh3ZtFFxOJYw3fo6PiFz4UMTEM69im0oHKsgGBm",
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default=history.entity.inventory_status.StatusName["NEW"],
                        max_length=128,
                    ),
                ),
                ("description", models.TextField(default=None)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("user_key_create", models.CharField(default=None, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "manufacturer_id",
                    models.CharField(
                        default="VUzw23Wbj7NaZzrparwT6PR26vaq1fy9G5GRemhAWrqUFppH1va1tN8zvk9oahSkUdbHAGEJ1TTARZCEKq5VweB2Zf1oKm7xjH9l2cU81LjDox2GMOfZ1JLP3i56Kn",
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("url", models.URLField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="OwnerOrganization",
            fields=[
                (
                    "street",
                    models.CharField(help_text="street address", max_length=128),
                ),
                ("city", models.CharField(max_length=64)),
                (
                    "province_state",
                    models.CharField(help_text="province/state/region", max_length=64),
                ),
                (
                    "country",
                    models.CharField(
                        default=history.entity.country.Country.default_number, max_length=32
                    ),
                ),
                ("phone_area_code", models.CharField(max_length=3)),
                ("phone_number", models.CharField(max_length=7)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "user_key_create",
                    models.CharField(
                        default="ytCUnydS6Eb3dypowO0at9Lb66JFasyuAvpFVZwTyWXIdRRe7HXrfQt5u9Y4zcXQpNomMtGhDBzokoRDqY7VYOXcrFhmr4HvJlvaCldHFC3ocNenFV2qBC7mom0KC2",
                        max_length=128,
                    ),
                ),
                (
                    "owner_organization_id",
                    models.CharField(
                        default="YKb9IjBZZK1P4pj583CFeUzPOQRq1luzNfJhbgjG9xwn8xrUmWJh80cRmbQozBjHhcFGtomXWnBkBwJxl8huwOvJzuL1LFmMK6fKJO6E9NSvvXgPtiN60X3XIbCkve",
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("url", models.URLField(default="")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OwnerPerson",
            fields=[
                (
                    "street",
                    models.CharField(help_text="street address", max_length=128),
                ),
                ("city", models.CharField(max_length=64)),
                (
                    "province_state",
                    models.CharField(help_text="province/state/region", max_length=64),
                ),
                (
                    "country",
                    models.CharField(
                        default=history.entity.country.Country.default_number, max_length=32
                    ),
                ),
                ("phone_area_code", models.CharField(max_length=3)),
                ("phone_number", models.CharField(max_length=7)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "user_key_create",
                    models.CharField(
                        default="ytCUnydS6Eb3dypowO0at9Lb66JFasyuAvpFVZwTyWXIdRRe7HXrfQt5u9Y4zcXQpNomMtGhDBzokoRDqY7VYOXcrFhmr4HvJlvaCldHFC3ocNenFV2qBC7mom0KC2",
                        max_length=128,
                    ),
                ),
                (
                    "owner_person_id",
                    models.CharField(
                        default="tWSqu38TtapfTuLEefyBI9GVDHbuPBQKuN4PWp0sfEmNlBawQBUaco2nXZB5ylg8ivPiS2DLPKNv4cCEnoseqXdnQpGMKTFcT3v1m4H1Hqlno7Ps5KS1kpboiOBQpI",
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("last_name", models.CharField(max_length=32)),
                ("first_name", models.CharField(max_length=64)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InventoryStatusAssign",
            fields=[
                (
                    "inventory_status_assign_id",
                    models.CharField(
                        default="2Xqk1EHSi7z95gH5kpCDzVwyA9KD2KOWPMbdmxJulbv5Wai8cSQO99K2o5FSbduox1hbHeRtsB75UkHSAD18LzMm2fXutQhjYrOtuqCRAuvIWuM2CIt7TIMV315ZM8",
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("user_key_create", models.CharField(default=None, max_length=128)),
                (
                    "inventory_item_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="history.inventoryitem",
                    ),
                ),
                (
                    "inventory_status_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="history.inventorystatus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryOwnership",
            fields=[
                (
                    "inventory_ownership_id",
                    models.CharField(
                        default="giXh32p3hFksuKlziuw6zTJHbW2lYMueKR6WNBTtN7nnlBoQgTxinYIwf26dhLHAKNpcILlk75uApA1PxRtt4lCm8f18jhLN2ij8It3OQnQqcZO2H65PwvW92uRBWc",
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_key_create", models.CharField(default=None, max_length=128)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("ownership_start", models.DateTimeField()),
                ("ownership_finish", models.DateTimeField()),
                (
                    "inventory_item_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="history.inventoryitem",
                    ),
                ),
                (
                    "owner_organization_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="history.ownerorganization",
                    ),
                ),
                (
                    "owner_person_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="history.ownerperson",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryNote",
            fields=[
                (
                    "inventory_note_id",
                    models.CharField(
                        default="aJLqzQbyJfqyx0GZU21oTbTbvrlsNksXm95XvPHq8YMf3FOgsVttoTVv9QWiwNibPxjg1SFrJkPMtjwTV5waEMaubX1Y9LDJdv9PvlTLLcncH0ANTPgBF6qHQoAgUa",
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_key_create", models.CharField(default=None, max_length=128)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("note", models.TextField()),
                (
                    "inventory_item_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="history.inventoryitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryLocationAssign",
            fields=[
                (
                    "inventory_location_assign_id",
                    models.CharField(
                        default="nm0Pwjdk69GqQK8KZRmPLTSwrt1WhFhkttcUTRS1utVLaKyXvTUGpQmP3xusAsC9Y0roMEHIkiv3q4vUVhQImStC9CloP6N0MenCjkc8nDzNphwjtP5AYuvSpQI3l9",
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("user_key_create", models.CharField(default=None, max_length=128)),
                (
                    "inventory_item_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="history.inventoryitem",
                    ),
                ),
                (
                    "inventory_location_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="history.inventorylocation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="inventory_status_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="history.inventorystatus",
            ),
        ),
        migrations.CreateModel(
            name="InventoryImage",
            fields=[
                (
                    "inventory_image_id",
                    models.CharField(
                        default="znlzPS5dKrPsBB5TkDnppZ14rcb6bixEOvNY8T9li4xT7zX7Oa3yASf6yXijojwd94o6DyOzTfMvizhhCEf22FV1C4B07vHpcnw9RoDgJnRZXZdfPrbyfCbm0QTvKS",
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_key_create", models.CharField(default=None, max_length=128)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(default=None, upload_to="images/inventory"),
                ),
                (
                    "inventory_item_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="history.inventoryitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GiftAgreement",
            fields=[
                (
                    "gift_agreement_id",
                    models.CharField(
                        default="q5DtsnqfhLgv1NWs68Tdvlybl8n4IILckk3e1v7zvEeEJyrHWC68CyjWilmQDyhG3h646oiaYsGXY1cXKBf76EszWfEbD0mycBgbFlIPaj7BqWOH0cbgyeBmHIMfVs",
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gift_agreement_number",
                    models.CharField(
                        default="3e5bYKilenoeRwGiJNnktfpgJTl1Yq73OA1YvM3U5OmoCfMk4a4XXWKREeFh1CE1exkW6p72ned7yEMyNaNXe1KPbGBow2CE2ahX1LLbK9y4JmJJ01axBTRQpM3pVH",
                        max_length=128,
                    ),
                ),
                ("user_key_create", models.CharField(default=None, max_length=128)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "inventory_item_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="history.inventoryitem",
                    ),
                ),
            ],
        ),
    ]
