# Generated by Django 4.2 on 2023-04-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_alter_inventoryitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
