# Generated by Django 4.2 on 2023-04-23 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_inventorystatus_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='status_id',
            new_name='inventory_status_id',
        ),
    ]
