# Generated by Django 4.2 on 2023-04-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_rename_status_id_inventoryitem_inventory_status_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryImage',
            fields=[
                ('inventory_image_id', models.CharField(primary_key=True, serialize=False, verbose_name=128)),
                ('inventory_item_id', models.CharField(verbose_name=128)),
                ('user_key_create', models.CharField(default=None, verbose_name=128)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryStatusAssign',
            fields=[
                ('inventory_status_assign_id', models.CharField(primary_key=True, serialize=False, verbose_name=128)),
                ('inventory_item_id', models.CharField(verbose_name=128)),
                ('inventory_status_id', models.CharField(verbose_name=128)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user_key_create', models.CharField(default=None, verbose_name=128)),
            ],
        ),
        migrations.AddField(
            model_name='inventorystatus',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inventorystatus',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='inventorystatus',
            name='user_key_create',
            field=models.CharField(default=None, verbose_name=128),
        ),
    ]
