# Generated by Django 4.2 on 2023-04-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0008_inventoryimage_inventorystatusassign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryimage',
            name='image',
            field=models.ImageField(default=None, upload_to='images/inventory'),
        ),
    ]
