# Generated by Django 4.2 on 2023-04-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0009_inventoryimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('inventory_location_id', models.CharField(primary_key=True, serialize=False, verbose_name=128)),
                ('name', models.CharField(verbose_name=128)),
                ('description', models.TextField(default=None)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user_key_create', models.CharField(default=None, verbose_name=128)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLocationAssign',
            fields=[
                ('inventory_location_assign_id', models.CharField(primary_key=True, serialize=False, verbose_name=128)),
                ('inventory_item_id', models.CharField(verbose_name=128)),
                ('inventory_location_id', models.CharField(verbose_name=128)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user_key_create', models.CharField(default=None, verbose_name=128)),
            ],
        ),
    ]
