# Generated by Django 4.2 on 2023-04-23 06:39

from django.db import migrations, models
from history.entity.inventory_status import StatusName


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0010_inventorylocation_inventorylocationassign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryimage',
            name='inventory_image_id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventoryimage',
            name='inventory_item_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='inventoryimage',
            name='user_key_create',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(help_text='a paragraph, eg. that would tell someone something interesting about the item'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='inventory_item_id',
            field=models.CharField(default=None, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='inventory_status_id',
            field=models.CharField(default=None, help_text='eg. available or not available for viewing', max_length=128),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(help_text='unique name, for conversational reference', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='url',
            field=models.URLField(help_text='if such exists, a url that we link to that provides more detail about the item', null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='user_key_create',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='inventorylocation',
            name='inventory_location_id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventorylocation',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='inventorylocation',
            name='user_key_create',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='inventorylocationassign',
            name='inventory_item_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='inventorylocationassign',
            name='inventory_location_assign_id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventorylocationassign',
            name='inventory_location_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='inventorylocationassign',
            name='user_key_create',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='inventorystatus',
            name='inventory_status_id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventorystatus',
            name='name',
            field=models.CharField(default=StatusName['NEW'], max_length=128),
        ),
        migrations.AlterField(
            model_name='inventorystatus',
            name='user_key_create',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='inventorystatusassign',
            name='inventory_item_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='inventorystatusassign',
            name='inventory_status_assign_id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventorystatusassign',
            name='inventory_status_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='inventorystatusassign',
            name='user_key_create',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
