# Generated by Django 4.2 on 2023-04-24 22:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import history.models
from history.entity.country import Country

class Migration(migrations.Migration):

    dependencies = [
        ('history', '0015_remove_donororganization_id_remove_donorperson_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('inventory_category_id', models.CharField(default='UhvWWulCIPoY4jTXZbSTctageGrhedz718QSl4eetkYvCW34tKtMiFIflG4WEUX6jF32AonSfWJA87YclOKD0I6ZzdGats0fWMCKLr6UqUtNr66oCGDxb2i0TpVlBD', max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('user_key_create', models.CharField(default=None, max_length=128)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default=None, upload_to='images/inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('manufacturer_id', models.CharField(default='IezLXtFV7ORjVxvhzzB4RfYA7jX1m1KjzhNIqHgbdxZLFDAkXc5PZeezHfjlAA3le2tl8McIk9ErazL3Kiq49WWKLswzHDL0XFENEWU35GUdTDHZQdyiIkcbhjhQcw', max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerOrganization',
            fields=[
                ('street', models.CharField(help_text='street address', max_length=128)),
                ('city', models.CharField(max_length=64)),
                ('province_state', models.CharField(help_text='province/state/region', max_length=64)),
                ('country', models.CharField(default=Country['CAN'], max_length=32)),
                ('phone_area_code', models.CharField(max_length=3)),
                ('phone_number', models.CharField(max_length=7)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user_key_create', models.CharField(default='JKTKDYn1KJuCrtHVRhvdeKIMOKfAUmLhmrTa0dm53LXEIV4v6INu87gPVTI4cjIaW4KXD1aMecQkv8rpoVIX9tm59sLsH0iOgfSK9kk9niSvrp86ZWYre2r8VX0gTs', max_length=128)),
                ('owner_organization_id', models.CharField(default='MqS4CF0QfMceANvw2cxKLLnIrbcT65uLud1YUGIl5gAvtcYQAv6UVcuajDTnEzrxV9aVErWChB0NjntB0REta3FerdEXT2RHpTX0cAJrasdAMMyCeYnqZ6qGQpcAWY', max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OwnerPerson',
            fields=[
                ('street', models.CharField(help_text='street address', max_length=128)),
                ('city', models.CharField(max_length=64)),
                ('province_state', models.CharField(help_text='province/state/region', max_length=64)),
                ('country', models.CharField(default=Country['CAN'], max_length=32)),
                ('phone_area_code', models.CharField(max_length=3)),
                ('phone_number', models.CharField(max_length=7)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user_key_create', models.CharField(default='JKTKDYn1KJuCrtHVRhvdeKIMOKfAUmLhmrTa0dm53LXEIV4v6INu87gPVTI4cjIaW4KXD1aMecQkv8rpoVIX9tm59sLsH0iOgfSK9kk9niSvrp86ZWYre2r8VX0gTs', max_length=128)),
                ('owner_person_id', models.CharField(default='2JL1xy4DH45ZAyWJkHY9rndfcl6rZJlMiBWHROseH3kz8R4LYHwQHdGAIy9dtepGyadGZtaFpwPlGvGgAi0KMGWSEgbe5jtwxRCmNelCOs3td0n4cqZUX7cp5SsWYe', max_length=128, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=32)),
                ('first_name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='accession_id',
            field=models.CharField(default=django.utils.timezone.now, help_text='unique identifier, eg. ISBN', max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='biography',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='length',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='manufactured_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='manufactured_in',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='manufactured_through',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='registered_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donororganization',
            name='donor_organization_id',
            field=models.CharField(default='NI9YJa13iLCoNobLB8XEdqBBl5NYmF5seTHQP2wy6EYiDrF6tdu0rvs01gKILhAO3MHkLPPLMU9jD9aRgYwiaQDPKxF0TmWi1H5jtDbspCoh8rwxGPvjsbaXLqkIhl', max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donororganization',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='donororganization',
            name='user_key_create',
            field=models.CharField(default='6oZwKGNfg2W8dz2FakLAVBj9Ae8LNBESTqaMsaA150yNOI28GGDVrAV4eiFul9CUy9r1e0y6Hx2GHXl77ML8elwO7CCoDO0QKRq9cS7QvwWp9qQJNTMqg3TAlVMnXv', max_length=128),
        ),
        migrations.AlterField(
            model_name='donorperson',
            name='donor_person_id',
            field=models.CharField(default='ILXrE7itVwjKXKPo1RsZRVT8TzCY51FzriR339WZQScdPaRVJHprpJtEoWaO6ozOtBtZ6XVEBuWGzycyAT20AoUQcWhv98lgiiV3mLRwCzRx4n4XE4UBhIaWplNF99', max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donorperson',
            name='user_key_create',
            field=models.CharField(default='6oZwKGNfg2W8dz2FakLAVBj9Ae8LNBESTqaMsaA150yNOI28GGDVrAV4eiFul9CUy9r1e0y6Hx2GHXl77ML8elwO7CCoDO0QKRq9cS7QvwWp9qQJNTMqg3TAlVMnXv', max_length=128),
        ),
        migrations.AlterField(
            model_name='inventoryimage',
            name='inventory_image_id',
            field=models.CharField(default='cXHvymMSZwaEgd32VOpILn3bnaArzpxLV155TU20dMp0diAliRJFUFfVcEtQ8O38MObt2qpHDuQjWKtNYtkLDuDIDWAMPNs2pNlVyDGYYq1zXnJgovDzSmeqtnQSXM', max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='inventory_item_id',
            field=models.CharField(default='dqLAwI7dPCZrlsPuRpETYZMYHzbIuxhBrHjCh3JDLPkyLUwAPtmxkgAwOlxKJX6vhP0HjEmsWQSc9nOm6MhS7yvv3pn2QwFmvoc29YOGAS9Z2FPU0UwxRx4Zq6dafy', max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventorylocation',
            name='inventory_location_id',
            field=models.CharField(default='wexTvwgWymWMWNAD6P4KsSvRFtzquAO1Idk7jymotOpi9yQmHSn5CNe3RlAosoAfwJhd362BM9qcrFbD7b8tu2PnKFWTYfezkAiz4q6WCpwFKgfCixbAkuRrv70Tc6', max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventorylocationassign',
            name='inventory_location_assign_id',
            field=models.CharField(default='SO752dquE6KCfoqrZLEFmlFeWm7xClY9M2n5yutTSoJI1TuZRqvZm61pUf3LlkdwNHvHUY4TFjGehTNzSw8ODgMBo0SvCxGGgv3EuFFsyYd56M8uVZkxZjl8xl1fvG', max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventorystatus',
            name='inventory_status_id',
            field=models.CharField(default='OdUIre5JiQP2g635UtjHEGeOlee244NM6zQ0Y3becb6I1OexXmEPXYGruSzBwROhUoYvQWIxZN7nd580M0YqHzxBZVWhz9VjVeu6OU8MNEtMOTpBjlSSFqsZD3m1Yz', max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventorystatusassign',
            name='inventory_status_assign_id',
            field=models.CharField(default='XfZ7Fk3FsH2Qs3Esxsrby5aCVxJYDetpInT6qX8CxZOunGMPTfSb9NQFqaGX7S7OnwNZCarfLRyyCjdA2Fy1BP00cml7CEUtAagLaQPe1rplIP90rN8lbUk8sdVdV9', max_length=128, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='InventoryOwnership',
            fields=[
                ('inventory_ownership_id', models.CharField(default='qJNZPvF6gRQt3ln9Rz2gzUta7ydQSxF4hrn9aanBygSgc2dEsoWsTM1bj6vRx5k8VuUPSGxTnLqd0HCk83Zd7sND7S4ZEy8Jhf7FxNSfzUL5ozi2vPaVAFSqQupmzU', max_length=128, primary_key=True, serialize=False)),
                ('user_key_create', models.CharField(default=None, max_length=128)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('ownership_start', models.DateTimeField()),
                ('ownership_finish', models.DateTimeField()),
                ('inventory_item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.inventoryitem')),
                ('owner_organization_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.ownerorganization')),
                ('owner_person_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.ownerperson')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryNote',
            fields=[
                ('inventory_note_id', models.CharField(default='FE4JRYWToPI5BifNLau7TMPPO74vqFn5KsKgwrM3Dwfn8kYdS6mclh8AL1HX8CK5Xnluz1Y1uBsrsPFqCF4PQKAjnUWn2GhJIkY5W0E8W4Fjg6Kn84yCC8AlJpybiK', max_length=128, primary_key=True, serialize=False)),
                ('user_key_create', models.CharField(default=None, max_length=128)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
                ('inventory_item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='GiftAgreement',
            fields=[
                ('gift_agreement_id', models.CharField(default='RSyNIMoKTY5T6gKnL9FWGVVJmPH4Pc2S3SBsD1IcNp2VdFvTcKrII87Cu26Wo1HlBx4SP7EF0aXCcA0iL3CrhNQGipbyLdyYqcsixL4NyjFpLBb1lSGwh6MW3ZpV3g', max_length=128, primary_key=True, serialize=False)),
                ('user_key_create', models.CharField(default=None, max_length=128)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('inventory_item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.inventoryitem')),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='inventory_category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.inventorycategory'),
        ),
    ]
